# Run all unittests

name: Unittests

on:
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # - name: Install tkinter
      #   run: sudo apt-get install xvfb python3-tk

      # - name: Install python packages
      #   run: pip3 install -r requirements.txt

      - name: Run tests
        run: ./test.sh
